spring:
  data:
    solr:
      host: http://192.168.2.2:8090/solr
  datasource:
    url: jdbc:mysql://localhost:3306/v1
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8071
#\u6CE8\u518C\u4E2D\u5FC3
dubbo:
  application:
    name: qf-v7-product-service
  registry:
    protocol: zookeeper
    address: 192.168.2.2:2181
  protocol:
    port: 28101
#\u6570\u636E\u5E93\u53C2\u6570
