server:
  port: 8070
#注册中心
dubbo:
  application:
    name: qf-v7-product-service
  registry:
    protocol: zookeeper
    address: 192.168.2.2:2181
  protocol:
    port: 28100
#数据库参数
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v1
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
