#\u6CE8\u518C\u4E2D\u5FC3
dubbo:
  application:
    name: qf-v7-user-service
  registry:
    protocol: zookeeper
    address: 192.168.2.2:2181
  protocol:
    port: 28105
#\u6570\u636E\u5E93\u53C2\u6570
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v1
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
#redis配置
  redis:
    host: 192.168.2.2
    port: 6379
    password: wutao
    jedis:
      pool:
        max-active: 88

server:
  port: 8074
