#\u914D\u7F6E\u670D\u52A1\u7AEF\u53E3
server:
  port: 8081

dubbo:
  application:
    name: wt-v1-search
  registry:
    protocol: zookeeper
    address: 192.168.2.2:2181

spring:
  thymeleaf:
    cache: false
fdfs:
  connect-timeout: 600
  so-timeout: 1500
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.2.2:22122


images:
  server: http://192.168.2.2/